name: Speed Comparison

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  benchmark:
    environment: ${{ github.ref == 'refs/heads/main' && 'Production' || 'Pull Requests' }}
    strategy: 
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    concurrency: 
      group: "speed-comparison-${{matrix.os}}"
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
          
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Build Single File
        run: dotnet publish SlowOsx64SingleFile.csproj -c Release --output singlefile-publish --property:SingleFile=true --runtime ${{ matrix.os == 'windows-latest' && 'win-x64' || matrix.os == 'ubuntu-latest' && 'linux-x64' || 'osx-x64' }}
        working-directory: "SlowOsx64SingleFile/SlowOsx64SingleFile"

      - name: Build Normal
        run: dotnet build -c Release
        working-directory: "SlowOsx64SingleFile/SlowOsx64SingleFile"
 
      - name: Run Benchmark
        run: ${{ matrix.os != 'windows-latest' && 'sudo -E ' || '' }}dotnet run -c Release
        working-directory: "SlowOsx64SingleFile/Benchmark"

      - name: Upload Markdown
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: markdown_${{ matrix.os }}
          path: |
            **/BenchmarkDotNet.Artifacts/**